(in-package :de.anvi.ansi-escape.test)

(defun t01 ()
  (erase)
  (cursor-position 5 15)
  (princ "test")
  (cursor-position 10 15)
  (force-output)
  (let ((a (read-line)))
    (cursor-position 12 15)
    (princ a)
    (force-output)))

(defun t02 ()
  (print "normal")
  (sgr 1)
  (print "bold")
  (sgr 4)
  (print "bold underline")
  (sgr 7)
  (print "bold underline reverse")
  (sgr 22)
  (print "underline reverse")
  (sgr 24)
  (print "reverse")
  (sgr 27)
  (print "normal")
  (sgr 1 4 7)
  (print "bold underline reverse")
  (sgr 0)
  (print "normal")
  (force-output))

